<div class="alert alert-info">
  <h1>methods for Creating numpy arrays</h1>
</div>

## Importing Numpy

In [2]:
import numpy as np

## Creating Numpy arrays

In [4]:
lst = [1,2,3]
np.array(lst)

array([1, 2, 3])

In [5]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
mat3d = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
np.array(mat3d)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
## array from range
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [114]:
list1 = [[1,2,3],['tom','jerry','jack'],[4,5,6]]
np.array(list1)

array([['1', '2', '3'],
       ['tom', 'jerry', 'jack'],
       ['4', '5', '6']], dtype='<U11')

### arange

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Zeros and Ones

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### eye 

In [26]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
mat = np.array([[1,2,3,4], [10,20,30,40], [25,35,45,55], [35,53,45,61]])
mat

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [25, 35, 45, 55],
       [35, 53, 45, 61]])

In [8]:
np.triu(mat)

array([[ 1,  2,  3,  4],
       [ 0, 20, 30, 40],
       [ 0,  0, 45, 55],
       [ 0,  0,  0, 61]])

In [9]:
np.tril(mat)

array([[ 1,  0,  0,  0],
       [10, 20,  0,  0],
       [25, 35, 45,  0],
       [35, 53, 45, 61]])

## linspace

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [30]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

## Random: creating random numbers arrays 

In [34]:
# rand
np.random.rand(3)

array([0.92740399, 0.90733161, 0.01417881])

In [39]:
np.random.rand(3,3)

array([[0.06176005, 0.0018924 , 0.12828819],
       [0.97802688, 0.76815437, 0.8491805 ],
       [0.8661674 , 0.132174  , 0.11343509]])

In [40]:
np.random.rand(4,2)

array([[0.33607446, 0.24199298],
       [0.42935366, 0.56420807],
       [0.79329543, 0.16406123],
       [0.24599961, 0.78023906]])

In [41]:
# randn

In [42]:
np.random.randn(2)

array([-0.53377072, -0.7393743 ])

In [43]:
np.random.randn(10)

array([-0.37989306,  0.79758781,  0.22544621, -0.6931128 , -0.03672333,
        0.80499306,  0.89155266, -0.5263505 ,  0.12252094, -0.74972459])

In [48]:
nums =  np.random.randn(5)

In [49]:
nums

array([-0.42543558,  1.44723242, -0.28388417,  0.54226092, -1.3070951 ])

In [50]:
np.random.randn(3,3)

array([[ 0.24091852,  2.00384533, -1.9211516 ],
       [-1.72721918, -0.35392846, -0.00934887],
       [-1.82596714, -0.84089514,  0.15843021]])

In [51]:
#randint

In [61]:
np.random.randint(1,10)

8

In [62]:
np.random.randint(1,100,10)

array([93, 36, 68, 49,  6, 53, 86, 48, 67, 69])

In [317]:
np.random.randint(0,2, 10)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0])

In [319]:
np.random.randint(10, size = (4,3))

array([[9, 9, 7],
       [8, 7, 5],
       [4, 3, 0],
       [4, 7, 8]])

## Saving and loading data

In [272]:
my_array = np.random.randint (1,100,100)

In [273]:
my_array

array([ 3, 59, 48, 24, 52, 15, 94, 21, 33, 16, 54, 96, 19,  4,  7, 88, 50,
        4, 72, 79, 44, 32, 79, 86, 18, 85, 78, 23, 29, 64, 12, 26, 57, 91,
       59, 88, 60, 93, 53, 10, 14, 35, 21, 11, 49, 81, 66, 71, 44, 62, 73,
       75, 51, 69, 79, 59, 62,  4, 89, 64, 14, 60, 67, 46, 37, 86,  2, 80,
       36, 75, 92, 91, 91, 93, 88, 36, 23, 52, 17, 72, 83, 85, 32, 73, 26,
        9, 91, 62, 82, 22, 88, 43, 18, 83, 68, 68, 19, 44, 75, 61])

In [275]:
np.save('my_array.npy', my_array)

In [278]:
a = np.load('my_array.npy')

In [279]:
a

array([ 3, 59, 48, 24, 52, 15, 94, 21, 33, 16, 54, 96, 19,  4,  7, 88, 50,
        4, 72, 79, 44, 32, 79, 86, 18, 85, 78, 23, 29, 64, 12, 26, 57, 91,
       59, 88, 60, 93, 53, 10, 14, 35, 21, 11, 49, 81, 66, 71, 44, 62, 73,
       75, 51, 69, 79, 59, 62,  4, 89, 64, 14, 60, 67, 46, 37, 86,  2, 80,
       36, 75, 92, 91, 91, 93, 88, 36, 23, 52, 17, 72, 83, 85, 32, 73, 26,
        9, 91, 62, 82, 22, 88, 43, 18, 83, 68, 68, 19, 44, 75, 61])