## Working with Arrays : Array Attributes and Methods

In [1]:
import numpy as np

### reshape

In [70]:
arr = np.arange(25)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr2d = arr.reshape(5,5)

In [73]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr_random = np.random.randint(0,40,10)

In [76]:
arr_random

array([ 8, 20, 27,  3,  4, 38, 25,  7, 26, 31])

In [79]:
arr_random.reshape(2,5)

array([[ 8, 20, 27,  3,  4],
       [38, 25,  7, 26, 31]])

In [78]:
np.random.randint(0,100,15).reshape(3,5)

array([[18, 32, 45, 16, 42],
       [13, 33, 97, 28, 51],
       [ 4, 37, 55, 72, 71]])

### max,min,argmax,argmin

In [82]:
arr_random = np.random.randint(0,40,10)
arr_random

array([29, 13, 35, 18, 36, 10, 33,  6, 24, 27])

In [83]:
arr_random.max()

36

In [84]:
arr_random.min()

6

In [85]:
arr_random.argmax()

4

In [86]:
arr_random.argmin()

7

### flatten

In [88]:
arr = np.random.randn(4,4)
arr

array([[ 0.10971895,  1.5475169 , -0.57833096,  0.50039699],
       [ 0.75543361, -1.69332558, -1.15024891,  1.57016987],
       [ 1.29221685, -0.17718897, -0.71362339,  0.32597875],
       [-1.57126749, -0.11934831,  1.69432782, -0.66750767]])

In [90]:
arr.shape

(4, 4)

In [91]:
arr.flatten()

array([ 0.10971895,  1.5475169 , -0.57833096,  0.50039699,  0.75543361,
       -1.69332558, -1.15024891,  1.57016987,  1.29221685, -0.17718897,
       -0.71362339,  0.32597875, -1.57126749, -0.11934831,  1.69432782,
       -0.66750767])

In [93]:
arr.flatten().shape

(16,)

### vstack,hstack,concatenate

In [94]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [95]:
a

array([[1, 2],
       [3, 4]])

In [96]:
b

array([[5, 6],
       [7, 8]])

In [97]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [98]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [101]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### hsplit(), vsplit()

In [297]:
c = np.arange(0,25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [306]:
np.hsplit(c, np.array([2,3]) )

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [307]:
np.hsplit(c, np.array([3,4]) )

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [309]:
d = np.arange(0,24).reshape(6,4)

In [311]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [312]:
np.vsplit(d, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [313]:
np.vsplit(d, np.array([1,3]))

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [314]:
# Split
np.split(c, np.array([3,4]), axis = 1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [315]:
np.split(c, np.array([3,4]), axis = 0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

### dtype attribute

In [108]:
my_arr = np.array([1,2,3,4])

In [103]:
my_arr.dtype

dtype('int32')

In [104]:
my_arr = np.array([1.5,2,3,4])

In [105]:
my_arr.dtype

dtype('float64')

In [109]:
my_arr = np.array([1,2,3,4], dtype='float64')

In [110]:
my_arr.dtype

dtype('float64')

In [111]:
my_sec_array = np.array([1.5,2.7,3.8,4,5,6],dtype = 'int32')

In [112]:
my_sec_array

array([1, 2, 3, 4, 5, 6])

# Operations on arrays

In [55]:
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.linspace(0,10,9).reshape(3,3)


In [56]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr2

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [116]:
arr1 + arr2

array([[ 0.  ,  2.25,  4.5 ],
       [ 6.75,  9.  , 11.25],
       [13.5 , 15.75, 18.  ]])

In [58]:
arr1 * arr2

array([[ 0.  ,  1.25,  5.  ],
       [11.25, 20.  , 31.25],
       [45.  , 61.25, 80.  ]])

In [59]:
arr1 / arr2

<ipython-input-59-4b2fbeb950c1>:1: RuntimeWarning: invalid value encountered in true_divide
  arr1 / arr2


array([[nan, 0.8, 0.8],
       [0.8, 0.8, 0.8],
       [0.8, 0.8, 0.8]])

Array with Scaler

In [202]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [204]:
arr -6

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [205]:
arr +10-6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [206]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [117]:
arr = np.array([1,2,3])

In [118]:
for x in arr:
    print(x)

1
2
3


In [119]:
arr = np.array([[1,2,3],[4,5,6]])

In [120]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


## Sorting arrays

In [288]:
a = np.random.randint(4,100,20)

In [289]:
a

array([ 7, 50, 99, 34, 68, 90,  8, 74, 90, 44, 94, 77, 27, 28, 31, 26, 41,
       36, 81, 77])

In [290]:
a.sort()

In [291]:
a

array([ 7,  8, 26, 27, 28, 31, 34, 36, 41, 44, 50, 68, 74, 77, 77, 81, 90,
       90, 94, 99])

In [292]:
b = np.random.randint(4,100,20).reshape(4,5)
b

array([[79, 84, 57,  6, 30],
       [94, 58, 11, 86, 30],
       [61, 82, 80, 80, 92],
       [73, 93, 81, 64, 68]])

In [293]:
b.sort(axis= 1)

In [294]:
b

array([[ 6, 30, 57, 79, 84],
       [11, 30, 58, 86, 94],
       [61, 80, 80, 82, 92],
       [64, 68, 73, 81, 93]])

In [295]:
b.sort(axis= 0)

In [296]:
b

array([[ 6, 30, 57, 79, 84],
       [11, 30, 58, 81, 92],
       [61, 68, 73, 82, 93],
       [64, 80, 80, 86, 94]])

### Universal Array Functions

In [209]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
np.max(arr)

10

In [211]:
arr.max()

10

In [212]:
np.min(arr)

0

In [234]:
np.median(arr)

5.0

In [235]:
np.std(arr)

3.1622776601683795

In [236]:
np.append([[1,2,3],[4,5,6]], [7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
np.append([[1,2,3],[4,5,6]], [[7,8,9]], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [239]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Math Functions

In [213]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [215]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [216]:
np.exp(arr) #e^

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [217]:
np.power(arr, 3)

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [218]:
np.log(arr)

<ipython-input-218-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [219]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [220]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

### delete

In [240]:
np.delete(arr, 1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [242]:
np.delete(arr, 3)

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr2 = np.arange(0,25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [244]:
np.delete(arr2,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [247]:
np.delete(arr2,[2,5])

array([ 0,  1,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [248]:
np.delete(arr2,[2], axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [249]:
np.delete(arr2,[2], axis = 1)

array([[ 0,  1,  3,  4],
       [ 5,  6,  8,  9],
       [10, 11, 13, 14],
       [15, 16, 18, 19],
       [20, 21, 23, 24]])

### insert

In [251]:
np.insert(arr, 2, 99)

array([ 0,  1, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.insert(arr2, 2, 99)

array([ 0,  1, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [254]:
np.insert(arr2, 2, 99, axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [99, 99, 99, 99, 99],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [260]:
np.insert(arr2, 2, 99, axis = 1)

array([[ 0,  1, 99,  2,  3,  4],
       [ 5,  6, 99,  7,  8,  9],
       [10, 11, 99, 12, 13, 14],
       [15, 16, 99, 17, 18, 19],
       [20, 21, 99, 22, 23, 24]])

In [21]:
arr3=np.insert(arr2, 2, 99, axis = 1)

In [22]:
arr3

array([[ 0,  1, 99,  2,  3,  4],
       [ 5,  6, 99,  7,  8,  9],
       [10, 11, 99, 12, 13, 14],
       [15, 16, 99, 17, 18, 19],
       [20, 21, 99, 22, 23, 24]])

In [23]:
np.delete(arr3, 2, axis = 1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
np.insert(arr3,1, [[ 11,  12, 88,  75,  33,  45]], axis = 0)

array([[ 0,  1, 99,  2,  3,  4],
       [11, 12, 88, 75, 33, 45],
       [ 5,  6, 99,  7,  8,  9],
       [10, 11, 99, 12, 13, 14],
       [15, 16, 99, 17, 18, 19],
       [20, 21, 99, 22, 23, 24]])

In [26]:
np.insert(arr3,[1], [[ 11,  12, 88,  75,  33,  45]], axis = 1)

array([[ 0, 11, 12, 88, 75, 33, 45,  1, 99,  2,  3,  4],
       [ 5, 11, 12, 88, 75, 33, 45,  6, 99,  7,  8,  9],
       [10, 11, 12, 88, 75, 33, 45, 11, 99, 12, 13, 14],
       [15, 11, 12, 88, 75, 33, 45, 16, 99, 17, 18, 19],
       [20, 11, 12, 88, 75, 33, 45, 21, 99, 22, 23, 24]])

In [28]:
np.insert(arr3,[2], [  [0], [0],  [0],  [0],  [0]], axis = 1)

array([[ 0,  1,  0, 99,  2,  3,  4],
       [ 5,  6,  0, 99,  7,  8,  9],
       [10, 11,  0, 99, 12, 13, 14],
       [15, 16,  0, 99, 17, 18, 19],
       [20, 21,  0, 99, 22, 23, 24]])

### Matrix Product   ************  **********

In [223]:
a = np.arange(1,6)
b = np.arange(2,7)
np.multiply(a,b)

array([ 2,  6, 12, 20, 30])

In [224]:
b

array([2, 3, 4, 5, 6])

In [225]:
np.matmul(a,b)

70

In [227]:
a = np.arange(0,25).reshape(5,5)
b = np.arange(1,6)

In [228]:
np.matmul(a,b)

array([ 40, 115, 190, 265, 340])

In [229]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [230]:
b

array([1, 2, 3, 4, 5])

### dot Product

In [232]:
c = np.array([1,2,3,4])
d = np.array([3,2,6,8])
np.dot(c,d)

57