## Numpy Indexing, Sclicing, and Selection

### Indexing 

In [65]:
arr = np.arange(15,25)

In [66]:
arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr[1]

16

In [68]:
arr[8]

23

In [71]:
arr[1:5]

array([16, 17, 18, 19])

In [72]:
arr[:7]

array([15, 16, 17, 18, 19, 20, 21])

In [73]:
arr[2:]

array([17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr[:]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr[2:9:2]

array([17, 19, 21, 23])

In [76]:
arr[::2]

array([15, 17, 19, 21, 23])

In [77]:
arr[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

### Brodcasting

In [82]:
lst = [1,2,3,4,5]
lst[1:4]=10

TypeError: can only assign an iterable

In [85]:
arr4 = np.arange(0,5)

In [86]:
arr4[1:4]= 10

In [87]:
arr4

array([ 0, 10, 10, 10,  4])

In [88]:
lst[1:4] = [10,10,10]

In [89]:
lst

[1, 10, 10, 10, 5]

### copy

#### Challenge

In [90]:
a = np.arange(0,11)

In [91]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
slice_a = a[0:5]
slice_a

array([0, 1, 2, 3, 4])

In [93]:
slice_a[:] = 999

In [94]:
slice_a

array([999, 999, 999, 999, 999])

In [95]:
a

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

### soultion with copy

In [97]:
b = np.arange(0,11)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
b_copy = b.copy()

In [99]:
b_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
b_copy[0:5] = 999

In [101]:
b_copy

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

In [102]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### indexing  2D arrays (matrices)

In [103]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
mat[1]

array([20, 25, 30])

In [105]:
mat[1][2]

30

In [106]:
mat[0]

array([ 5, 10, 15])

In [109]:
mat[0][1:3]

array([10, 15])

In [111]:
mat[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [122]:
# caution
mat[0:2][1:3]

array([[20, 25, 30]])

In [127]:
mat[1:3][1]

array([35, 40, 45])

In [128]:
mat[1:3][1][2]

45

In [129]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [130]:
mat.transpose()

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [132]:
m = np.arange(0,100).reshape(10,10)

In [133]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
m[3:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [135]:
m[3:][0]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

### double slicing

In [136]:
m[3:,4:]

array([[34, 35, 36, 37, 38, 39],
       [44, 45, 46, 47, 48, 49],
       [54, 55, 56, 57, 58, 59],
       [64, 65, 66, 67, 68, 69],
       [74, 75, 76, 77, 78, 79],
       [84, 85, 86, 87, 88, 89],
       [94, 95, 96, 97, 98, 99]])

In [137]:
m[3:6,4:7]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56]])

In [138]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### <font color='red'>Fancy indexing</font>

In [146]:
m[2:8]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [147]:
m[2:8:2]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [148]:
m[[2,4,6]]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [164]:
m[[1,6]][:,1:4]

array([[11, 12, 13],
       [61, 62, 63]])

In [165]:
m[[1,6], 1:4]

array([[11, 12, 13],
       [61, 62, 63]])

In [175]:
m[[2,4],3:6]

array([[23, 24, 25],
       [43, 44, 45]])

In [174]:
m[1:3,[1,4,7]]

array([[11, 14, 17],
       [21, 24, 27]])

In [169]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
# method 1
m[[1,3]][:,[1,4,7]]

array([[11, 14, 17],
       [31, 34, 37]])

In [189]:
m[[1,3], [[1],[4],[7]]]  # not coerrect

array([[11, 31],
       [14, 34],
       [17, 37]])

In [186]:
# method 2
m[[[1], [3]], [1,4,7]]

array([[11, 14, 17],
       [31, 34, 37]])

In [187]:
# method 2
m[[1,3],:][:,[1,4,7]]

array([[11, 14, 17],
       [31, 34, 37]])

## Selection (query)

In [192]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [193]:
arr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [194]:
arr == 15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False])

In [195]:
cond = arr>7

In [196]:
cond

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [197]:
arr[cond]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [198]:
arr[arr>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [199]:
a = 10
arr[arr == a]

array([10])

In [200]:
arr[arr <= 5]

array([1, 2, 3, 4, 5])

In [201]:
arr[arr %3 ==0]

array([ 3,  6,  9, 12, 15, 18])

## changing the values according to a criteria

In [11]:
mat = np.arange(1,26).reshape(5,5)

In [14]:
np.where(mat<10,mat,mat*10)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [15]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
np.where(mat>10,mat,mat*10)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [ ]:
Indexing and se